ALTER TABLE persons
    ADD COLUMN IF NOT EXISTS father_id UUID REFERENCES persons(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS mother_id UUID REFERENCES persons(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS spouse_id  UUID REFERENCES persons(id) ON DELETE SET NULL;
